language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - LLIST=llist
  - LLIST=git+https://github.com/fuzeman/pypy-llist.git

install:
  - mkdir .install; pushd .install; git clone https://github.com/rogerbinns/apsw.git apsw; pushd apsw; python setup.py fetch --all --missing-checksum-ok build --enable-all-extensions install; popd; popd;
  - pip install $LLIST
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -r requirements_travis.txt

script:
  - coverage run -m py.test -m "not slow"

after_success:
  - coveralls