language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - LLIST=llist
  - LLIST=pyllist

install:
  - mkdir .install; pushd .install; git clone https://github.com/rogerbinns/apsw.git apsw; pushd apsw; python setup.py fetch --all build --enable-all-extensions install; popd; popd;
  - pip install $LLIST
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install -r requirements_travis.txt

script:
  - coverage run -m py.test

after_success:
  - coveralls